/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#494bd6",
        "on-tertiary-container": "#fffbff",
        "on-primary-container": "#fffbff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f0f3ff",
        "primary-fixed": "#e1e0ff",
        "on-secondary-fixed": "#141b2c",
        "outline-variant": "#c7c4d7",
        "secondary-fixed": "#dbe2fa",
        "primary-container": "#6063ee",
        "on-error": "#ffffff",
        "background": "#f9f9ff",
        "on-tertiary-fixed-variant": "#703700",
        "on-secondary-container": "#5d6478",
        "tertiary-container": "#b55d00",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-background": "#111c2d",
        "surface-bright": "#f9f9ff",
        "surface": "#f9f9ff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d8e3fb",
        "secondary-fixed-dim": "#bfc6dd",
        "primary-fixed-dim": "#c0c1ff",
        "secondary": "#575e72",
        "surface-container": "#e7eeff",
        "on-tertiary-fixed": "#301400",
        "on-surface-variant": "#464554",
        "tertiary-fixed-dim": "#ffb783",
        "on-primary-fixed": "#07006c",
        "secondary-container": "#dbe2fa",
        "tertiary": "#904900",
        "error-container": "#ffdad6",
        "surface-dim": "#cfdaf2",
        "on-primary": "#ffffff",
        "inverse-surface": "#263143",
        "inverse-primary": "#c0c1ff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#3f4759",
        "outline": "#767586",
        "inverse-on-surface": "#ecf1ff",
        "on-surface": "#111c2d",
        "tertiary-fixed": "#ffdcc5",
        "primary": "#4648d4",
        "surface-container-high": "#dee8ff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#d8e3fb",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "container-max": "1280px",
        "unit": "4px",
        "xl": "40px",
        "md": "16px",
        "xs": "4px",
        "lg": "24px",
        "gutter": "24px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "h1": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "h2": ["Plus Jakarta Sans"],
        "h3": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "h1": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "h2": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "h3": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
